sources:
  - Ubuntu.designspace
  - Ubuntu-Italic.designspace
axisOrder:
  - wdth
  - wght
  - ital
familyName: Ubuntu
buildStatic: false
outputDir: ../fonts/Ubuntu
stat:
  - name: Width
    tag: wdth
    values:
    - name: Condensed
      value: 75
    - name: Normal
      value: 100
  - name: Weight
    tag: wgth
    values:
    - name: Thin
      value: 100
    - name: Light
      value: 300
    - name: Regular
      value: 400
      linkedValue: 700
    - name: Medium
      value: 500
    - name: Bold
      value: 700